stages:
  - test
  - build image
  - deploy

variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  MYSQL_ROOT_PASSWORD: "root"
  MYSQL_DATABASE: "ota_treehub"
  MYSQL_USER: "treehub"
  MYSQL_PASSWORD: "treehub"
  SBT_OPTS: "-sbt-launch-dir .sbt/launchers -sbt-dir .sbt -ivy .ivy2 -Dsbt.color=true -Dscala.color=true"
  SERVICE: treehub

image: registry.gitlab.com/torizon-platform/ci-container-build:scala-jvm17-0.0.5

include:
  - project: torizon-platform/ci-container-build
    file: gitlab-ci-templates/gitlab-sbt-docker-publish.yaml
    ref: master
  - project: 'torizon-platform/deploy-env'
    ref: master
    file: '/gitlab/deploy-core-service.yml'

services:
  - name: docker:dind
  - name: mariadb:10.4
    alias: db
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci
      - --max_connections=1000

default:
  cache:
    key: treehub
    when: always
    paths:
      - .ivy2/
      - .sbt/

test:
  stage: test
  rules:
    - if: $CI_COMMIT_REF_NAME == "master"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  variables:
    DB_URL: "jdbc:mariadb://db:3306/ota_treehub"
  before_script:
    - echo "GRANT ALL PRIVILEGES ON \`ota\_treehub%\`.* TO 'treehub'@'%'; FLUSH PRIVILEGES;" > db_user.sql
    - until mysqladmin ping --protocol=TCP -h db -P 3306 -u root -proot; do echo waiting for mysql; sleep 1; done
    - mysql -v -h db -u root -proot < db_user.sql
  script:
    - sbt ut:test

build docker image:
  stage: build image
  rules:
    - if: $CI_COMMIT_REF_NAME == "master"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  extends: .sbt-docker-publish
  variables:
    SERVICE_NAME: treehub
